url: https://italyshiddengems.com
baseurl:

# Site settings
title: Italy's Hidden Gems
email: travel@italyshiddengems.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Additional collections (besides posts)
collections:
  next_trips:
    output: true
    permalink: /next_trips/:path/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: tripadvisor
    url: https://www.tripadvisor.com/Attraction_Review-g187879-d27800411-Reviews-Italy_s_Hidden_Gems-Sardinia.html
  - title: instagram
    url: https://www.instagram.com/italyshiddengems/
  - title: facebook
    url: https://www.facebook.com/lvinti85IHG
  - title: substack
    url: https://italyshiddengems.substack.com/

# Postal address (add as many lines as necessary)
address:
  - line: 4445 Corporation Ln STE 264
  - line: Virginia Beach, VA 23462

# Build settings
markdown: kramdown
permalink: pretty